# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: trc-data-reader

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage coverage-badge
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Coverage with coverage
      run: |
        coverage run --source src -m unittest discover
        coverage report -m
        git clone https://github.com/hsorby/badges.git badges
        coverage-badge -o badges/trc-data-reader/coverage.svg
        cd badges
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Updating trc-data-reader coverage badge." -a
        git push https://hsorby:${BADGES_PAT}@github.com/hsorby/badges.git master
      env:
        BADGES_PAT: ${{ secrets.BADGES_REPO_PERSONAL_ACCESS_TOKEN }}
